# Generated by Selenium IDE
import math

from selenium import webdriver
from selenium.webdriver.common.by import By
import time

def calc(x):
  return str(math.log(abs(12 * math.sin(int(x)))))

class TestYandex:
  def setup_method(self, method):
    self.driver = webdriver.Chrome()

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ya(self):
    self.driver.get("http://suninjuly.github.io/math.html")
    self.driver.maximize_window()

    x_element = self.driver.find_element(By.CSS_SELECTOR, "#input_value")
    x = x_element.text
    y = calc(x)

    self.driver.find_element(By.CSS_SELECTOR, "#answer").send_keys(y)

    self.driver.find_element(By.CSS_SELECTOR, "[for='robotCheckbox']").click()

    self.driver.find_element(By.ID, 'robotsRule').click()

    self.driver.find_element(By.CSS_SELECTOR, "[type='submit']").click()

    time.sleep(30)
    